language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-29.0.3
    - android-30
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+

script:
   - ./gradlew build connectedCheck
