language: android
dist: trusty
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools-29.0.3
    - build-tools-29.0.3
    - android-30
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
script: ./gradlew assembleDebug lintDebug
