language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - tools
    - build-tools-29.0.2
    - android-29
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+
    
before_install:
    - chmod +x gradlew

script:
    - chmod +x ./gradlew build connectedCheck
