language: android
dist: trusty
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools-29.0.6
    - build-tools-29.0.3
    - android-29
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
script: ./gradlew -Dorg.gradle.jvmargs=-Xmx1536m assembleDebug lintDebug
